mapping_mode: 3
lidar_topic: "/velodyne_points"
frame_id:
  map: "map"
  robot: "base_link"
  odom: "odom"
  lidar: "velodyne"

preprocess:
  minZ_: -3.0
  maxZ_: 4.0

local_map:
  resolution: 0.2
  mapLengthX: 40.0
  mapLengthY: 60.0

global_map:
  resolution: 0.2
  mapLengthX: 2000
  mapLengthY: 2000
  submapLengthX: 60
  submapLengthY: 80
  sensorRangeLimit: 40
  predictionKernalSize: 0.3

minZ: -3.0
maxZ: 3.0
lidar_Z: 0
heightdiff_threshold: 0.6
cntratiothreshold: 0.5
threadCount: 4
normal_estimationRadius: 2.0